name: Automatically build and publish this plugin

on:
  push:
    branches:
      - 'master'

jobs:

  build-and-publish-plugin:
    runs-on: ubuntu-latest
    name: Build and publish plugin
    permissions:
      contents: write
    steps:

    # Execute plugin repo gen action
    - name: Build and publish plugin
      uses: Unmanic/action.build-and-publish-unmanic-plugin@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
